#!/bin/bash

# Grab full name of workspace container
WORKSPACE_CONTAINER=$(docker ps | grep workspace | awk '{print $1}')

# Grab OS type
if [[ "$(uname)" == "Darwin" ]]; then
    OS_TYPE="OSX"
else
    OS_TYPE=$(expr substr $(uname -s) 1 5)
fi

DIR=$1
URL=$3
DB_NAME=$4

magento_dev() {
    CMD="pwd && cd $DIR && pwd \\
        && echo 'deploy:mode:set developer' \\
        && php -dxdebug.mode=off bin/magento deploy:mode:set developer \\
        && echo 'Disable Magento_TwoFactorAuth' \\
        && php -dxdebug.mode=off bin/magento module:disable --clear-static-content Magento_TwoFactorAuth\\
        && echo 'Enable admin account sharing' \\
        && php -dxdebug.mode=off bin/magento config:set admin/security/admin_account_sharing 1\\
        && echo 'admin/security/use_form_key 0' \\
        && php -dxdebug.mode=off bin/magento config:set admin/security/use_form_key 0\\
        && echo 'admin/security/session_lifetime 31536000' \\
        && php -dxdebug.mode=off bin/magento config:set admin/security/session_lifetime 31536000\\
        && echo 'admin/security/password_is_forced 0' \\
        && php -dxdebug.mode=off bin/magento config:set admin/security/password_is_forced 0\\
        && echo 'admin/security/password_lifetime forever' \\
        && php -dxdebug.mode=off bin/magento config:set admin/security/password_lifetime ''"


    if [[ $OS_TYPE == "MINGW" ]]; then
        winpty docker exec --user=laradock -it $WORKSPACE_CONTAINER bash -c "${CMD}"

    else
        docker exec --user=laradock -it $WORKSPACE_CONTAINER bash -c "${CMD}"
    fi
}

magento_install() {
    if [[ $URL == "" || $DB_NAME == "" ]]; then
        echo "Synctax error: magento DIR install BASE_URL DB_NAME"

        return
    fi

    echo "URL: $URL"
    echo "DB_NAME: $DB_NAME"

    EXECUTE_PHP="\$dbh = new PDO(\"mysql:host=mysql\", \"root\", \"root\");\
    \$dbh->exec(\"CREATE DATABASE IF NOT EXISTS $DB_NAME DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci\");"
    CMD="pwd && cd $DIR && pwd \\
        && php -dxdebug.mode=off -r '$EXECUTE_PHP' \\
        && bin/magento setup:install \\
        --base-url=$URL \\
        --db-host=mysql \\
        --db-name=$DB_NAME \\
        --db-user=root \\
        --db-password=root \\
        --backend-frontname=admin \\
        --admin-use-security-key=0 \\
        --admin-firstname=admin \\
        --admin-lastname=admin \\
        --admin-email=admin@admin.com \\
        --admin-user=admin \\
        --admin-password=Admin@123 \\
        --language=en_US \\
        --currency=USD \\
        --timezone=America/Chicago \\
        --use-rewrites=1 \\
        --search-engine=elasticsearch7 \\
        --elasticsearch-host=elasticsearch \\
        --elasticsearch-port=9200"

    if [[ $OS_TYPE == "MINGW" ]]; then
        winpty docker exec --user=laradock -it $WORKSPACE_CONTAINER bash -c "${CMD}"

    else
        docker exec --user=laradock -it $WORKSPACE_CONTAINER bash -c "${CMD}"
    fi
}

case $2 in
dev | DEV)
    magento_dev
    ;;
install | INSTALL)
    magento_install
    ;;
*)
    echo "Config for Magento environment for ${WORKSPACE_CONTAINER} container."
    echo "Magento 2 must have already been installed."
    echo "Usage:"
    echo "  ./magento project_directory dev"
    ;;

esac

exit 1
